"""SQLAlchemy-backed conversation share storage (#4548).

Each method acquires its own short-lived session. The raw bearer token is
generated by the app layer and passed in only as its HMAC-SHA-256 digest;
this repository never sees the token itself.
"""

from __future__ import annotations

import logging
import uuid
from datetime import UTC, datetime
from typing import Any

from sqlalchemy import func, select, update
from sqlalchemy.dialects.postgresql import insert as pg_insert
from sqlalchemy.dialects.sqlite import insert as sqlite_insert
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker

from deerflow.persistence.conversation_shares.model import ConversationShareQuota, ConversationShareRow
from deerflow.utils.time import coerce_iso

logger = logging.getLogger(__name__)

_DATETIME_FIELDS = ("expires_at", "revoked_at", "created_at", "updated_at")

# Columns the owner-facing management list projects. The response reads
# id/title and the lifecycle timestamps only, so the heavy payload
# (``snapshot_json``, capped at the share limit per row) and the token hash
# are deliberately never loaded by the listing query — a thread with many
# (including revoked) shares must stay cheap to list no matter how large the
# snapshots are.
_SUMMARY_DATETIME_FIELDS = ("expires_at", "revoked_at", "created_at")


class ConversationShareRepository:
    def __init__(self, session_factory: async_sessionmaker[AsyncSession]) -> None:
        self._sf = session_factory

    @staticmethod
    def _row_to_dict(row: ConversationShareRow) -> dict[str, Any]:
        d = row.to_dict()
        for key in _DATETIME_FIELDS:
            val = d.get(key)
            if isinstance(val, datetime):
                # SQLite drops tzinfo on read; normalize so output is tz-aware.
                d[key] = coerce_iso(val)
        return d

    @staticmethod
    def _summary_row_to_dict(row: Any) -> dict[str, Any]:
        """Map a metadata-projection row, normalizing datetimes like full rows."""
        d = {
            "id": row.id,
            "title": row.title,
            "expires_at": row.expires_at,
            "revoked_at": row.revoked_at,
            "created_at": row.created_at,
        }
        for key in _SUMMARY_DATETIME_FIELDS:
            val = d[key]
            if isinstance(val, datetime):
                d[key] = coerce_iso(val)
        return d

    async def create(
        self,
        *,
        thread_id: str,
        owner_user_id: str,
        token_hash: str,
        title: str,
        snapshot_json: dict[str, Any],
        snapshot_version: int = 1,
        source_last_seq: int | None = None,
        expires_at: datetime | None = None,
        quota_limit: int | None = None,
    ) -> dict[str, Any] | None:
        """Insert one share row, atomically capped per owner.

        ``quota_limit`` enforces the owner's stored-row cap inside this
        insert's transaction: admission is a single guarded upsert on the
        owner's counter row, so concurrently racing creations serialize on
        the counter instead of each passing a pre-checked count and all
        inserting. Returns ``None`` when the owner is already at the cap.
        ``None`` admits uncapped — direct/test use; the router always
        passes the configured cap (plus its cheap indexed pre-check so
        over-quota requests never pay for the snapshot scan).
        """
        now = datetime.now(UTC)
        row = ConversationShareRow(
            id=str(uuid.uuid4()),
            thread_id=thread_id,
            owner_user_id=owner_user_id,
            token_hash=token_hash,
            title=title,
            snapshot_version=snapshot_version,
            snapshot_json=snapshot_json,
            source_last_seq=source_last_seq,
            expires_at=expires_at,
            created_at=now,
            updated_at=now,
        )
        async with self._sf() as session:
            async with session.begin():
                if quota_limit is not None and not await self._admit_share_slot(session, owner_user_id, quota_limit):
                    return None
                session.add(row)
            await session.refresh(row)
            return self._row_to_dict(row)

    @staticmethod
    async def _admit_share_slot(session: AsyncSession, owner_user_id: str, quota_limit: int) -> bool:
        """Atomic quota admission: one guarded upsert statement.

        The cap lives in the upsert's WHERE clause, so ``stored_shares``
        only ever increments below it; rowcount 0 means the owner is at the
        cap. Runs in the caller's transaction — a later insert failure
        rolls the admission back with it.
        """
        bind = session.bind
        if bind is None:  # pragma: no cover - sessions here are always bound
            raise RuntimeError("quota admission requires a bound session")
        if bind.dialect.name == "postgresql":
            upsert = pg_insert(ConversationShareQuota)
        elif bind.dialect.name == "sqlite":
            upsert = sqlite_insert(ConversationShareQuota)
        else:  # pragma: no cover - the config only offers these backends
            raise ValueError(f"unsupported database backend for share quota: {bind.dialect.name}")
        result = await session.execute(
            upsert.values(owner_user_id=owner_user_id, stored_shares=1).on_conflict_do_update(
                index_elements=[ConversationShareQuota.owner_user_id],
                set_={ConversationShareQuota.stored_shares: ConversationShareQuota.stored_shares + 1},
                where=ConversationShareQuota.stored_shares < quota_limit,
            )
        )
        return result.rowcount == 1

    async def get_active_by_token_hash(self, token_hash: str) -> dict[str, Any] | None:
        """Return the non-revoked, non-expired share for *token_hash*.

        Revocation and expiry are evaluated on every public request: a share
        that has been revoked or has passed ``expires_at`` resolves to ``None``
        here even though its row remains readable for owner-side history.
        Liveness is decided by a light probe (id + expiry only, revocation
        filtered in SQL) and the full row — snapshot payload included — is
        fetched only for live shares, so a retained token for a dead share
        never materializes its payload no matter how large the snapshots are.
        """
        async with self._sf() as session:
            probe = (
                await session.execute(
                    select(ConversationShareRow.id, ConversationShareRow.expires_at).where(
                        ConversationShareRow.token_hash == token_hash,
                        ConversationShareRow.revoked_at.is_(None),
                    )
                )
            ).first()
            if probe is None:
                return None
            expires_at = probe.expires_at
            if expires_at is not None:
                # SQLite drops tzinfo on read; normalize before comparing.
                if expires_at.tzinfo is None:
                    expires_at = expires_at.replace(tzinfo=UTC)
                if expires_at <= datetime.now(UTC):
                    return None
            row = (await session.execute(select(ConversationShareRow).where(ConversationShareRow.id == probe.id))).scalar_one()
            return self._row_to_dict(row)

    async def get(self, share_id: str) -> dict[str, Any] | None:
        """Return one share row by id regardless of lifecycle state."""
        async with self._sf() as session:
            row = (await session.execute(select(ConversationShareRow).where(ConversationShareRow.id == share_id))).scalar_one_or_none()
            return self._row_to_dict(row) if row is not None else None

    async def list_by_thread(self, thread_id: str, owner_user_id: str) -> list[dict[str, Any]]:
        """List a thread's shares for the owner's management view.

        Projects only the summary columns (id, title, and the lifecycle
        timestamps) — never the snapshot payload or the token hash — so the
        listing cost is independent of snapshot sizes and of how many shares
        (revoked rows included, for history) a thread accumulates. Ordered
        newest first; ``expires_at`` / ``revoked_at`` let the UI show active
        vs. revoked links.
        """
        async with self._sf() as session:
            rows = (
                await session.execute(
                    select(
                        ConversationShareRow.id,
                        ConversationShareRow.title,
                        ConversationShareRow.expires_at,
                        ConversationShareRow.revoked_at,
                        ConversationShareRow.created_at,
                    )
                    .where(
                        ConversationShareRow.thread_id == thread_id,
                        ConversationShareRow.owner_user_id == owner_user_id,
                    )
                    .order_by(ConversationShareRow.created_at.desc())
                )
            ).all()
            return [self._summary_row_to_dict(row) for row in rows]

    async def count_by_owner(self, owner_user_id: str) -> int:
        """Count every stored row for *owner_user_id*, across threads and
        lifecycle states.

        The create-path quota reads this: revocation is soft (rows keep their
        snapshot payload for owner-side history), so only counting all rows
        bounds the per-account storage footprint.
        """
        async with self._sf() as session:
            return int(await session.scalar(select(func.count()).select_from(ConversationShareRow).where(ConversationShareRow.owner_user_id == owner_user_id)) or 0)

    async def revoke(self, share_id: str, thread_id: str, owner_user_id: str) -> bool:
        """Revoke one of *owner_user_id*'s shares; False if absent/not owned.

        Revocation is effective immediately for every future public request.
        """
        async with self._sf() as session:
            result = await session.execute(
                update(ConversationShareRow)
                .where(
                    ConversationShareRow.id == share_id,
                    ConversationShareRow.thread_id == thread_id,
                    ConversationShareRow.owner_user_id == owner_user_id,
                    ConversationShareRow.revoked_at.is_(None),
                )
                .values(revoked_at=datetime.now(UTC), updated_at=datetime.now(UTC))
            )
            await session.commit()
            return result.rowcount != 0
