
services:
  pgvector:
    image: docker.io/library/postgres:16-alpine 
    platform: linux/amd64
    container_name: postgres16
    restart: unless-stopped
    environment:
      POSTGRES_USER: pgsql
      POSTGRES_PASSWORD: pgsql
      POSTGRES_DB: pgsql
      PGDATA: /var/lib/postgresql/data/pgdata  # 数据目录
    ports:
      - "5432:5432"
    volumes:
      - /Users/raidery/data/postgres15:/var/lib/postgresql/data  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pgsql -d pgsql"]
      interval: 5s
      timeout: 5s
      retries: 5

