# /Users/luole/deer-flow/sample_config.yaml
# Configuration for the DeerFlow application
config_version: 5
log_level: info
token_usage:
  enabled: false

# Add your model configuration here (see config.example.yaml for examples)
models: []

tool_groups:
  - name: web
  - name: file:read
  - name: file:write
  - name: bash

tools:
  - name: web_search
    group: web
    use: deerflow.community.ddg_search.tools:web_search_tool
    max_results: 5
  - name: web_fetch
    group: web
    use: deerflow.community.jina_ai.tools:web_fetch_tool
    timeout: 10
  - name: image_search
    group: web
    use: deerflow.community.image_search.tools:image_search_tool
    max_results: 5
  - name: ls
    group: file:read
    use: deerflow.sandbox.tools:ls_tool
  - name: read_file
    group: file:read
    use: deerflow.sandbox.tools:read_file_tool
  - name: write_file
    group: file:write
    use: deerflow.sandbox.tools:write_file_tool
  - name: str_replace
    group: file:write
    use: deerflow.sandbox.tools:str_replace_tool
  - name: bash
    group: bash
    use: deerflow.sandbox.tools:bash_tool

tool_search:
  enabled: false

# THIS IS THE KEY SETTING YOU NEED TO CHANGE!
sandbox:
  use: deerflow.sandbox.local:LocalSandboxProvider
  allow_host_bash: true  # Set this to true to enable bash commands!
  bash_output_max_chars: 20000
  read_file_output_max_chars: 50000

skills:
  container_path: /mnt/skills

title:
  enabled: true
  max_words: 6
  max_chars: 60
  model_name: null

summarization:
  enabled: true
  model_name: null
  trigger:
    - type: tokens
      value: 15564