
FROM python:3.12-slim


WORKDIR /app/backend


COPY . .


RUN pip install --no-cache-dir --upgrade -r /app/backend/requirements-fastapi.txt




CMD ["uvicorn app.gateway.app:app --host 0.0.0.0 --port 8001"]