/**
 * Sanitization functions for ECharts options.
 * These clean up invalid format strings and fix dataset-related issues
 * that may be generated by AI models.
 */

/**
 * Strip invalid D3/Python-style format strings that AI models sometimes generate.
 * e.g. "${value:,.0f}" -> removed, "${c:,.2f}" -> removed, "{c[0]}" -> "{c}"
 */
export function sanitizeFormatters(obj: unknown): unknown {
  if (obj === null || obj === undefined) return obj;
  if (typeof obj === "string") {
    // Remove D3/Python format specifiers: ${value:,.0f}, ${c:,.2f}, etc.
    let s = obj.replace(/\$\{[^}]*:[^}]*\}/g, "");
    // Fix {c[0]}, {c[1]} -> {c}
    s = s.replace(/\{([abcd])\[\d+\]\}/g, "{$1}");
    return s;
  }
  if (Array.isArray(obj)) return obj.map(sanitizeFormatters);
  if (typeof obj === "object") {
    const result: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(obj as Record<string, unknown>)) {
      // Remove formatter keys that are entirely broken format strings
      if (k === "formatter" && typeof v === "string" && /^\$\{[^}]*:[^}]*\}$/.test(v.trim())) {
        continue; // drop the formatter entirely -- let ECharts auto-format
      }
      result[k] = sanitizeFormatters(v);
    }
    return result;
  }
  return obj;
}

/**
 * When using dataset+encode, ECharts dumps ALL columns into the tooltip.
 * This extracts encoded dimension names and sets seriesLayoutBy/dimensions
 * so the tooltip only shows relevant columns.
 */
export function fixDatasetTooltip(opt: Record<string, unknown>): Record<string, unknown> {
  const dataset = opt.dataset as { source?: unknown[][] } | undefined;
  const series = opt.series as Record<string, unknown>[] | undefined;
  if (!dataset?.source || !series) return opt;

  // Collect all encoded dimension names across series
  const encodedDims = new Set<string>();
  for (const s of series) {
    const encode = s.encode as Record<string, string | string[]> | undefined;
    if (!encode) continue;
    for (const vals of Object.values(encode)) {
      const arr = Array.isArray(vals) ? vals : [vals];
      for (const v of arr) {
        if (typeof v === "string") encodedDims.add(v);
      }
    }
  }

  if (encodedDims.size === 0) return opt;

  // Set tooltip dimensions to only encoded ones
  const header = dataset.source[0] as string[];
  if (!header || !Array.isArray(header)) return opt;

  const dimIndices = header
    .map((h, i) => (encodedDims.has(String(h)) ? i : -1))
    .filter((i) => i >= 0);

  // Add encode.tooltip to each series to limit tooltip dimensions
  const fixedSeries = series.map((s) => {
    const encode = s.encode as Record<string, unknown> | undefined;
    if (!encode || encode.tooltip) return s;
    // Set tooltip to show only the value dimensions (not x/itemName)
    const xDim = encode.x ?? encode.itemName;
    const tooltipDims = dimIndices
      .map((i) => header[i])
      .filter((d) => {
        const xArr = Array.isArray(xDim) ? xDim : [xDim];
        return !xArr.includes(d);
      });
    if (tooltipDims.length > 0) {
      return { ...s, encode: { ...encode, tooltip: tooltipDims } };
    }
    return s;
  });

  return { ...opt, series: fixedSeries };
}

/**
 * Strip explicit color overrides from chart options so ECharts themes can apply.
 * Removes `color` from top-level, from each series, and from series[].itemStyle.
 * Preserves colors in visualMap and other structural uses.
 */
export function stripExplicitColors(opt: Record<string, unknown>): Record<string, unknown> {
  const result = { ...opt };

  // Remove top-level color array (theme provides this)
  delete result.color;

  // Strip colors from series (but preserve markPoint/markLine/markArea annotation colors)
  const series = result.series;
  if (Array.isArray(series)) {
    result.series = series.map((s: Record<string, unknown>) => {
      const cleaned = { ...s };
      delete cleaned.color;
      if (cleaned.itemStyle && typeof cleaned.itemStyle === "object") {
        const style = { ...(cleaned.itemStyle as Record<string, unknown>) };
        delete style.color;
        delete style.color0;
        delete style.borderColor;
        delete style.borderColor0;
        cleaned.itemStyle = Object.keys(style).length > 0 ? style : undefined;
      }
      // Strip color from series data items (pie/donut charts)
      if (Array.isArray(cleaned.data)) {
        cleaned.data = (cleaned.data as unknown[]).map((item) => {
          if (item && typeof item === "object" && !Array.isArray(item)) {
            const d = { ...(item as Record<string, unknown>) };
            delete d.itemStyle;
            return d;
          }
          return item;
        });
      }
      // Preserve markPoint, markLine, markArea (annotation colors are intentional)
      // These are already in `cleaned` via the spread — just ensure they survive
      return cleaned;
    });
  }

  return result;
}

/**
 * When using dataset+encode, {c} in label.formatter dumps the entire row as
 * comma-separated text. Strip or fix label formatters on series when dataset
 * is present.
 */
export function fixDatasetLabels(opt: Record<string, unknown>): Record<string, unknown> {
  const dataset = opt.dataset as { source?: unknown[][] } | undefined;
  const series = opt.series as Record<string, unknown>[] | undefined;
  if (!dataset?.source || !series) return opt;

  const header = dataset.source[0] as string[];
  if (!header || !Array.isArray(header)) return opt;

  const fixedSeries = series.map((s) => {
    const label = s.label as Record<string, unknown> | undefined;
    if (!label) return s;

    const formatter = label.formatter;
    if (typeof formatter !== "string") return s;

    // {c} in dataset mode dumps the entire row; ${...} patterns are also invalid.
    // Remove the formatter and let ECharts auto-format.
    if (formatter.includes("{c}") || /\$\{/.exec(formatter)) {
      return { ...s, label: { ...label, formatter: undefined } };
    }

    return s;
  });

  return { ...opt, series: fixedSeries };
}
