"""skill mutation publication journal

Revision ID: 0028_skill_mutations
Revises: 0027_completed_run_evidence
Create Date: 2026-09-21 11:28:24.923105

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0028_skill_mutations"
down_revision: str | Sequence[str] | None = "0027_completed_run_evidence"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _create_table(name, *columns):
    # Legacy databases may already contain tables from an older create_all.
    inspector = sa.inspect(op.get_bind())
    if not inspector.has_table(name):
        op.create_table(name, *columns)
    else:
        existing = {column["name"] for column in inspector.get_columns(name)}
        required = {column.name for column in columns if isinstance(column, sa.Column)}
        if not required <= existing:
            raise RuntimeError(f"Incompatible preexisting skill mutation table: {name}")


def _create_index(name, table, columns):
    if name not in {index["name"] for index in sa.inspect(op.get_bind()).get_indexes(table)}:
        op.create_index(name, table, columns, unique=False)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    _create_table(
        "skill_mutation_assets",
        sa.Column("target_ref", sa.String(length=32), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("incarnation_id", sa.String(length=32), nullable=False),
        sa.Column("mutation_seq", sa.Integer(), nullable=False),
        sa.Column("content_digest", sa.String(length=64), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("mutating", sa.Boolean(), nullable=False),
        sa.Column("operation_id", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("target_ref"),
        sa.UniqueConstraint("owner_id", "name", name="uq_skill_asset_owner_name"),
    )
    _create_index("ix_skill_mutation_assets_owner_id", "skill_mutation_assets", ["owner_id"])

    _create_table(
        "skill_mutation_operations",
        sa.Column("operation_id", sa.String(length=32), nullable=False),
        sa.Column("plugin_id", sa.String(length=128), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("target_ref", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("method", sa.String(length=16), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("proposal_id", sa.String(length=32), nullable=True),
        sa.Column("reverts_operation_id", sa.String(length=32), nullable=True),
        sa.Column("before_operation_id", sa.String(length=32), nullable=True),
        sa.Column("before_revision", sa.JSON(), nullable=False),
        sa.Column("after_revision", sa.JSON(), nullable=False),
        sa.Column("before_blob", sa.LargeBinary(), nullable=True),
        sa.Column("after_blob", sa.LargeBinary(), nullable=True),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("publication", sa.String(length=16), nullable=False),
        sa.Column("views", sa.String(length=16), nullable=False),
        sa.Column("superseded_by_generation", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("rollback_expires_at", sa.Float(), nullable=False),
        sa.Column("assessment", sa.JSON(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("operation_id"),
        sa.UniqueConstraint("plugin_id", "method", "idempotency_key", name="uq_skill_operation_key"),
        sa.UniqueConstraint("proposal_id"),
    )
    _create_index("ix_skill_mutation_operations_owner_id", "skill_mutation_operations", ["owner_id"])
    _create_index("ix_skill_mutation_operations_publication", "skill_mutation_operations", ["publication"])

    _create_table(
        "skill_mutation_owners",
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("deleting", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("owner_id"),
    )
    _create_table(
        "skill_mutation_proposals",
        sa.Column("proposal_id", sa.String(length=32), nullable=False),
        sa.Column("plugin_id", sa.String(length=128), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("target_ref", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("base_revision", sa.JSON(), nullable=False),
        sa.Column("sources", sa.JSON(), nullable=False),
        sa.Column("candidate_hash", sa.String(length=64), nullable=False),
        sa.Column("package_blob", sa.LargeBinary(), nullable=True),
        sa.Column("candidate_blob", sa.LargeBinary(), nullable=True),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("expires_at", sa.Float(), nullable=False),
        sa.Column("check_result", sa.JSON(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("operation_id", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("proposal_id"),
        sa.UniqueConstraint("plugin_id", "idempotency_key", name="uq_skill_proposal_key"),
    )
    _create_index("ix_skill_mutation_proposals_owner_id", "skill_mutation_proposals", ["owner_id"])

    _create_table(
        "skill_mutation_scan_attempts",
        sa.Column("token", sa.String(length=32), nullable=False),
        sa.Column("plugin_id", sa.String(length=128), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("subject", sa.String(length=80), nullable=False),
        sa.Column("started_at", sa.Float(), nullable=False),
        sa.Column("lease_until", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("token"),
    )
    _create_index("ix_skill_mutation_scan_attempts_owner_id", "skill_mutation_scan_attempts", ["owner_id"])
    _create_index("ix_skill_mutation_scan_attempts_plugin_id", "skill_mutation_scan_attempts", ["plugin_id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("skill_mutation_scan_attempts")
    with op.batch_alter_table("skill_mutation_proposals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_skill_mutation_proposals_owner_id"))

    op.drop_table("skill_mutation_proposals")
    op.drop_table("skill_mutation_owners")
    with op.batch_alter_table("skill_mutation_operations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_skill_mutation_operations_publication"))
        batch_op.drop_index(batch_op.f("ix_skill_mutation_operations_owner_id"))

    op.drop_table("skill_mutation_operations")
    with op.batch_alter_table("skill_mutation_assets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_skill_mutation_assets_owner_id"))

    op.drop_table("skill_mutation_assets")
    # ### end Alembic commands ###
