"""create enterprise audit_events table

Revision ID: 20260518_m2_audit
Revises:
Create Date: 2026-05-18

Plan M2-3. Creates the ``audit_events`` table that backs
:class:`deerflow.enterprise.audit.storage.AuditEventRow`. The table is
the bedrock of the enterprise audit log (RFC §5.2).

Index choices
=============

Two compound indexes are explicit rather than autogenerated:

- ``ix_audit_events_user_timestamp`` covers "events for user X in time
  window Y" — the dominant query for the operator dashboard.
- ``ix_audit_events_type_timestamp`` covers "events of type Z in time
  window Y" — the dominant query for compliance exports (e.g. "all
  ``data.exported`` rows last quarter").

We deliberately do NOT index ``resource`` in v1; the cardinality is
high and the query patterns are still being shaped by RFC §9.1. Add it
in a follow-up revision once a real use case justifies the write cost.

``details`` is TEXT JSON
========================

We persist ``details`` as plain TEXT instead of JSONB so the same
migration runs unchanged on SQLite (tests / on-prem demos) and Postgres
(production). Server-side JSON path lookups are not required by any
v1 query path; if they become necessary, ALTER TABLE on Postgres can
introduce a generated JSONB column without breaking the SQLite path.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# Alembic identifiers — chosen to be human-greppable rather than the
# default random hash so a new operator can map revisions to plan rows.
revision = "20260518_m2_audit"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=64), primary_key=True),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=True),
        sa.Column("resource", sa.String(length=256), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=True),
        sa.Column("details", sa.Text(), nullable=False, server_default="{}"),
        sa.Column("signature", sa.String(length=128), nullable=True),
    )
    op.create_index(
        "ix_audit_events_user_timestamp",
        "audit_events",
        ["user_id", "timestamp"],
    )
    op.create_index(
        "ix_audit_events_type_timestamp",
        "audit_events",
        ["event_type", "timestamp"],
    )


def downgrade() -> None:
    # Drop indexes first — Postgres doesn't strictly require it (CASCADE
    # would work) but SQLite cleanup is simpler this way, and it keeps
    # the downgrade symmetric with upgrade.
    op.drop_index("ix_audit_events_type_timestamp", table_name="audit_events")
    op.drop_index("ix_audit_events_user_timestamp", table_name="audit_events")
    op.drop_table("audit_events")
