import logging
from urllib.parse import quote

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import HTMLResponse, PlainTextResponse, Response

from src.storage import extract_file_from_skill_archive_bytes, get_thread_file_backend, guess_mime_type, is_text_bytes

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api", tags=["artifacts"])


@router.get(
    "/threads/{thread_id}/artifacts/{path:path}",
    summary="Get Artifact File",
    description="Retrieve an artifact file generated by the AI agent. Supports text, HTML, and binary files.",
)
async def get_artifact(thread_id: str, path: str, request: Request) -> Response:
    """Get an artifact file by its path.

    The endpoint automatically detects file types and returns appropriate content types.
    Use the `?download=true` query parameter to force file download.

    Args:
        thread_id: The thread ID.
        path: The artifact path with virtual prefix (e.g., mnt/user-data/outputs/file.txt).
        request: FastAPI request object (automatically injected).

    Returns:
        The file content as a FileResponse with appropriate content type:
        - HTML files: Rendered as HTML
        - Text files: Plain text with proper MIME type
        - Binary files: Inline display with download option

    Raises:
        HTTPException:
            - 400 if path is invalid or not a file
            - 403 if access denied (path traversal detected)
            - 404 if file not found

    Query Parameters:
        download (bool): If true, returns file as attachment for download

    Example:
        - Get HTML file: `/api/threads/abc123/artifacts/mnt/user-data/outputs/index.html`
        - Download file: `/api/threads/abc123/artifacts/mnt/user-data/outputs/data.csv?download=true`
    """
    artifact_backend = get_thread_file_backend("artifact_reads")

    # Check if this is a request for a file inside a .skill archive (e.g., xxx.skill/SKILL.md)
    if ".skill/" in path:
        # Split the path at ".skill/" to get the ZIP file path and internal path
        skill_marker = ".skill/"
        marker_pos = path.find(skill_marker)
        skill_file_path = path[: marker_pos + len(".skill")]  # e.g., "mnt/user-data/outputs/my-skill.skill"
        internal_path = path[marker_pos + len(skill_marker) :]  # e.g., "SKILL.md"

        try:
            skill_exists = artifact_backend.exists_virtual_file(thread_id, f"/{skill_file_path.lstrip('/')}")
        except PermissionError as e:
            raise HTTPException(status_code=403, detail=str(e)) from e

        if not skill_exists:
            raise HTTPException(status_code=404, detail=f"Skill file not found: {skill_file_path}")

        # Extract the file from the .skill archive
        try:
            skill_bytes = artifact_backend.read_virtual_file(thread_id, f"/{skill_file_path.lstrip('/')}")
        except PermissionError as e:
            raise HTTPException(status_code=403, detail=str(e)) from e
        content = extract_file_from_skill_archive_bytes(skill_bytes, internal_path)
        if content is None:
            raise HTTPException(status_code=404, detail=f"File '{internal_path}' not found in skill archive")

        # Determine MIME type based on the internal file
        mime_type = guess_mime_type(internal_path)
        # Add cache headers to avoid repeated ZIP extraction (cache for 5 minutes)
        cache_headers = {"Cache-Control": "private, max-age=300"}
        if mime_type and mime_type.startswith("text/"):
            try:
                return PlainTextResponse(content=content.decode("utf-8"), media_type=mime_type, headers=cache_headers)
            except UnicodeDecodeError:
                return Response(content=content, media_type="application/octet-stream", headers=cache_headers)

        # Default to plain text for unknown types that look like text
        try:
            return PlainTextResponse(content=content.decode("utf-8"), media_type="text/plain", headers=cache_headers)
        except UnicodeDecodeError:
            return Response(content=content, media_type=mime_type or "application/octet-stream", headers=cache_headers)

    virtual_path = f"/{path.lstrip('/')}"
    logger.info(f"Resolving artifact path: thread_id={thread_id}, requested_path={path}, backend={type(artifact_backend).__name__}")

    try:
        exists = artifact_backend.exists_virtual_file(thread_id, virtual_path)
    except PermissionError as e:
        raise HTTPException(status_code=403, detail=str(e)) from e

    if not exists:
        raise HTTPException(status_code=404, detail=f"Artifact not found: {path}")

    try:
        content = artifact_backend.read_virtual_file(thread_id, virtual_path)
    except PermissionError as e:
        raise HTTPException(status_code=403, detail=str(e)) from e
    mime_type = guess_mime_type(path)

    # Encode filename for Content-Disposition header (RFC 5987)
    filename = path.rstrip("/").split("/")[-1]
    encoded_filename = quote(filename)

    # if `download` query parameter is true, return the file as a download
    if request.query_params.get("download"):
        return Response(content=content, media_type=mime_type or "application/octet-stream", headers={"Content-Disposition": f"attachment; filename*=UTF-8''{encoded_filename}"})

    if mime_type and mime_type == "text/html":
        try:
            return HTMLResponse(content=content.decode("utf-8"))
        except UnicodeDecodeError:
            return Response(content=content, media_type=mime_type)

    if mime_type and mime_type.startswith("text/"):
        try:
            return PlainTextResponse(content=content.decode("utf-8"), media_type=mime_type)
        except UnicodeDecodeError:
            return Response(content=content, media_type="application/octet-stream")

    if is_text_bytes(content):
        try:
            return PlainTextResponse(content=content.decode("utf-8"), media_type=mime_type)
        except UnicodeDecodeError:
            return Response(content=content, media_type="application/octet-stream")

    return Response(content=content, media_type=mime_type, headers={"Content-Disposition": f"inline; filename*=UTF-8''{encoded_filename}"})
